@extends('layouts.site.core')
@section('title', __('general/legal.terms_of_use'))
@section('body')
<div class="container">
	<div class="row">
	    <div class="col col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
	        <div class="ui-block">
	            <article class="post">
	                <h4>{{__('general/legal.terms_of_use')}}</h4>
	                <p>
	                    
	                    <h2>General</h2><br>
	                    {{config('app.name')}}, LLC (herein after referred to as “{{config('app.name')}}”) has established these Terms of Use, Provisions, and Conditions (which also incorporate by reference, without limitation, Our Privacy Policy, Subpoena Compliance Policy, and DMCA Notice &amp;  Takedown Policy) (hereinafter referred to collectively as “Terms of Use or “TOU””) to govern Your use of this Site and all affiliated sites and every mobile version hereof or thereof (collectively, “Site,” this “Site,” “the Site,” or the “Service”) whether or not You are a registered user of this Site.&nbsp; {{config('app.name')}} reserves the right, at its sole discretion, to change, modify, add, or delete portions of these TOU, and to notify You of such changes by modifying the “Last Revised” date at the top of this TOU.  You acknowledge that it is Your responsibility to review the “Last Revised” date to determine if any changes have been made since Your last review of this TOU.  By accessing and continuing to use the Site after the change to this TOU, You thereby manifest Your agreement to any changes hereto. <br><br>
	                    By entering this Site, You acknowledge that (a) You have read and understand these TOU and that You agree to be bound by the TOU as same may be amended from time to time; (b) You shall comply with all applicable laws and regulations; and (c) the disclaimer, limitation of liability, and indemnification provisions set forth in the TOU are an agreed upon allocation of risk and form an essential part of our agreement to permit You to use this Site, without which agreement {{config('app.name')}} would not enter into this Agreement or permit You to use this Site.  If You do not agree to be bound by the TOU, You are directed to terminate and discontinue Your use of this Site immediately.&nbsp; 
	                    {{config('app.name')}} DOES NOT PERFORM CRIMINAL BACKGROUND OR SEX OFFENDER CHECKS ON ANY PROSPECTIVE USER, PUBLISHER, OR THIRD PARTY.   You are encouraged to use common sense when interacting with any individual located through this Site.  {{config('app.name')}} is not responsible for activities, claims, or losses that result from meeting individuals identified through the Site.<br><br>
	                    “Publishers” have registered with {{config('app.name')}} and have been granted authority to use the Service to publish photographs and videos and to use other services and features associated with a Publisher account.  Publishers are required to separately register, and provide specific information required by {{config('app.name')}}.  {{config('app.name')}} reserves the right to require agreement to additional terms and provisions by Publishers before acceptance.  Publishers are not agents or employees of {{config('app.name')}} and {{config('app.name')}} has absolutely no relationship with said Publishers other providing a platform for them to self-publish and collect coins.  A User's correspondence and/or dealings (business or otherwise) with the Publishers found on or through this Site are solely between the User and such Publisher.  {{config('app.name')}} shall not be responsible or liable for loss or damage of any sort whatsoever incurred by You or any third party as the result of such dealings or as the result of the advertisements place on the Site. <br><br>
	                    You may not copy, reproduce, republish, transmit, disseminate, reverse engineer, reverse assemble, sell, or distribute in any way any material from this Site, including, without limitation, photographs, video, code, and software.&nbsp; You may in certain instances be permitted to upload information, photographs, and/or video to this Site subject to the express conditions hereof.<br><br>
	                    <h2>Information Related to Minors</h2><br><br>
	                    {{config('app.name')}} will not allow the publishing, of any information relating to individuals under the age of eighteen (18) years.&nbsp; {{config('app.name')}} will not knowingly collect information, personal or otherwise, from individuals under the age of eighteen (18) years.&nbsp; By using this Site, You certify, that You are over the age of eighteen (18) years.&nbsp; The United States and various foreign, federal, state, and local jurisdictions impose significant penalties upon individuals and entities who contribute to the proliferation or use of pornography related to minors.&nbsp; If You seek underage material, please exist the site immediately.  YOU ARE HEREBY NOTIFIED THAT, TO THE EXTENT REQUIRED BY APPLICABLE LAW, {{config('app.name')}} WILL COOPERATE IN THE INVESTIGATION OF ANY UNLAWFUL USE OF THE SITE OR ITS SERVICES.  Any suspected underage material found on this Site should be reported asacp.org or to the CyberTip Hotline; http://www.missingkids.com/cybertipline <br><br>
	                    <h2>Registration Data; Account Security</h2><br><br>
	                    In consideration of Your use of this Site, You agree to (a) provide accurate, current and complete information about You as may be prompted by any registration forms on the Site (“Registration Information”); (b) maintain the security of Your password and account credentials; (c) maintain and promptly update the Registration Information, and any other information You provide to {{config('app.name')}}, to keep it accurate, current, and complete; and (d) be fully responsible for all use of Your account and for any actions that take place using Your account.  Account credentials may not be used by more than one User.  In the event a User is found to have shared account credentials with another person, the User's account may be terminated for breach of this Agreement.  {{config('app.name')}} reserves the right to suspend or terminate Your access to this Site at any time for any violation of these TOU.<br><br>
	                    <h2>Payment Methods</h2><br><br>
	                    Payment for the services and products, if any, purchased on this Site may be made by credit card or any payment set forth on our payment page.&nbsp;&nbsp; Billing may be performed by a third-party payment processor.  For credit card payments, you will be required to provide us with the exact billing address and telephone number that Your credit card issuer has on file for You.&nbsp; You may further be required to provide us with the security code on Your credit card. &nbsp;You authorize us and our agents to transact payments on Your behalf. Incorrect information may cause a delay in processing, or denial of, Your order. &nbsp;We reserve the right to suspend Service to You in the event You have provided inaccurate or incomplete credit card information, or if Your payment information is out of date.<br><br>

	                    <h2>Correction of Errors and Inaccuracies</h2><br><br>
	                    The information on this Site may contain typographical errors or inaccuracies and may not be complete or current. &nbsp;{{config('app.name')}} reserves the right to correct any errors, inaccuracies, or omissions and to change or update information at any time. &nbsp;Unless intended by the context of the display, the incidental display of products in this Site shall not constitute an endorsement by {{config('app.name')}} of such products.  <br><br>
	                    
	                    <h2>Manner of Conduct</h2><br><br>
	                   You may not mirror any materials contained on this Site without prior written permission of {{config('app.name')}}.&nbsp; You may not use any robot, spider, or other automatic device or manual process to screen scrape, monitor, mine, or copy any of the web pages of this Site, any advertisements, any profiles, or any content hereon.&nbsp; Because the harm caused by violations of this section are not easily measured, You agree to pay a liquidated damages fee of $25,000 if You violate this term.  The parties agree that this liquidated damages provision is not a penalty, but is instead an attempt to reasonably anticipate the amount of actual damages that might be sustained by {{config('app.name')}} in the event of a breach of this provision. <br><br> 
	                    You represent, warrant, covenant, and agree that no materials of any kind submitted through Your account or otherwise posted, transmitted, or shared by You on this Site will violate or infringe upon the rights of any third party, including copyright, trademark, privacy, publicity, or other personal or proprietary rights; or contain libelous, defamatory, or otherwise unlawful material.&nbsp; You shall not use or distribute pirated or unauthorized User Content, photographs, products or information. 
	                    Governing Law; &nbsp;Severability; Entire Agreement; Statute of Limitations:<br><br>
	                    THESE TERMS OF USE, PROVISIONS AND CONDITIONS AND YOUR AGREEMENT WITH {{config('app.name')}} SHALL BE GOVERNED BY THE LAWS OF THE STATE OF CALIFORNIA, WITHOUT REGARD TO ITS CONFLICTS OF LAWS PROVISIONS. &nbsp;YOU AGREE TO BE SUBJECT TO SUCH LAWS AND THAT VENUE IN ANY ACTION OR PROCEEDING COMMENCED PURSUANT TO THIS AGREEMENT SHALL LIE IN FORT LAUDERDALE, CALIFORNIA, AND YOU IRREVOCABLY CONSENT TO THE EXCLUSIVE JURISDICTION OF THE FEDERAL AND STATE COURTS SITTING IN SUCH VENUE.&nbsp; YOU HEREBY CONSENT TO THE PERSONAL JURISDICTION OF THE FEDERAL AND STATE COURTS SITTING IN FORT LAUDERDALE, CALIFORNIA. <br><br>
	                    If any provision or portion thereof set forth in these TOU is found to be unlawful, void, or for any other reason unenforceable, then such provision or portion thereof shall be deemed severable and shall not affect the validity and enforceability of any other provision.&nbsp; Such severable provision shall be construed as nearly as possible to reflect the intention of these terms of use, provisions, or conditions. <br><br>
	                    This Agreement and any policies or documents incorporated into the Agreement by specific reference serves as the entire agreement between the parties and may be amended upon notice by {{config('app.name')}}.  {{config('app.name')}} may provide notice by E- mail, conventional mail, or by a general posting (indicated by the word “Notice”) on its web page, but is not obligated to do so.<br><br>
	                    To the extent permitted by applicable law, You agree that, by using this Site, regardless of any statute or law to the contrary, any claim or cause of action that You may have arising out of, in connection with, or relating to, Your use of this Site and/or these TOU must be filed within one (1) year after the claim or cause of action accrued or such claim or cause of action shall forever be barred.<br><br>
	                    <h2>Indemnity</h2><br><br>
	                    You shall indemnify, defend, and hold harmless {{config('app.name')}} and its affiliates and their respective&nbsp; shareholders, directors, attorneys, members, managers, officers, employees and agents and their respective successors and/or assigns from and against any and all losses, liabilities, claims, suits, damages, judgments, fines, penalties, violations, actions, causes of action, proceedings, demands, costs, and expenses (including, without limitation, reasonable attorney’s fees, court costs, and disbursements) (collectively, “Claims”), arising out of, resulting from, or in connection with, Your use of this Site and/or any third party Sites and/or Your use of the products or services, if any, obtained through Your use of the Site.   In any claim subject to indemnification hereunder, {{config('app.name')}} shall control the defense (including settlement of claims).  {{config('app.name')}} shall be permitted to retain legal counsel of its choice in any claim subject to indemnification.  <br><br>
	                    <h2>Ownership &amp; Trademarks</h2><br><br>
	                    The name “{{config('app.name')}}” and related names and marks are service marks owned by and may not be used in connection with any third-party marks, names, products, services, or otherwise.&nbsp; “{{config('app.name')}}” is a registered trademark of {{config('app.name')}}.&nbsp; All other marks and names (including third-party product marks and names) are the property of their respective owners.<br><br>
	                    Copyrights; Use of Content:<br><br>
	                    All software used to operate or display this Site is the property of {{config('app.name')}} or is licensed to {{config('app.name')}}, and is protected by United States and international copyright laws. &nbsp;The compilation, collection, selection, arrangement, assembly, and coordination of all the text, graphics, photographs, graphs, sounds, data, images, audio, and video clips available on this site except for Publisher Content is the exclusive property of {{config('app.name')}} and protected by United States and international copyright laws.&nbsp; © {{date('Y')}} by {{config('app.name')}}, LLC.; ALL RIGHTS RESERVED. We respect the intellectual property rights of all parties, and have adopted a policy regarding termination of repeat copyright infringers under the Digital Millennium Copyright Act.  Copies of Our Repeat Infringer Policy are available on request to Our Members.<br><br>
	                    <h2>Links and Linking</h2><br><br>
	                    Some websites which are linked to the Site are owned and operated by third parties. Because We have no control over such websites and resources, You acknowledge and agree that We are not responsible or liable for the availability of such external websites or resources, and do not screen or endorse them, and are not responsible or liable for any content, advertising, services, products, or other materials on or available from such websites or resources.<br><br>
	                    You further acknowledge and agree that We shall not be responsible or liable, directly or indirectly, for any damage or loss caused or alleged to be caused by or in connection with use of or reliance on any such third-party content, goods or services available on or through any such website or resource.  If You decide to access any such third-party website, You do so entirely at Your own risk and subject to any terms and conditions and privacy policies posted therein. 
	                    You further acknowledge that use of any website controlled, owned or operated by third parties is governed by the terms and conditions of use for those websites, and not by this Agreement. <br><br>
	                    Links to external websites (including external websites that are framed by the Site) or inclusions of advertisements do not constitute an endorsement by Us of such websites or the content, products, advertising, or other materials presented on such Site, but are for Your convenience.<br><br>
	                    You hereby agree to hold Us harmless from any and all damages and liability that may result from the use of links that may appear on the Site or via the Services. We reserve the right to terminate any link or linking program at any time.  <br><br>
	                    <h2>Disclaimer</h2><br><br>
	                    This Site and its contents, and the links to third-party sites and their contents, are provided on a strictly “as-is” and “as-available” basis and without warranties or representations of any kind, express or implied.&nbsp; <br><br>
	                    To the maximum extent permitted by law, {{config('app.name')}} specifically disclaims all representations and warranties, express, implied, or otherwise, including, without limitation, implied warranties of merchantability or fitness for a particular purpose and non-infringement, and implied warranties from course of dealing or performance and any warranties as to results that may be obtained through use of this Site or third-party sites.&nbsp; No information or advice obtained from {{config('app.name')}}, whether written or oral, shall create any warranty from {{config('app.name')}}.<br><br>
	                    {{config('app.name')}} expects users to take responsibility for their own actions and, accordingly, {{config('app.name')}} does not assume any liability whatsoever for the acts of third parties or those publishing on the Site and assumes no liability whatsoever for any replies or any actions arising out of any material published on the Site.&nbsp; &nbsp;&nbsp;You waive any and all claims, rights, or remedies which You otherwise might have or be able to assert against {{config('app.name')}} under all applicable laws, rules, and regulations that arise out of or in any way relate to Publisher Content, Your use of the Site, and {{config('app.name')}}’s response or failure to respond to any complaint You may make in connection therewith or otherwise.
	                    {{config('app.name')}} does not warrant that the functions contained in the materials furnished on this Site or any third-party site will be uninterrupted, available, or error-free, that defects or errors will be corrected, or that this Site will be available, free from viruses or other harmful components.&nbsp; {{config('app.name')}} shall not be responsible or liable for any threatening, defamatory, obscene, offensive, or illegal content or conduct of any Publisher or other party or any infringement of another’s rights, including, without limitation, intellectual property or similar rights.&nbsp; Your use of this Site is strictly at Your own risk, which is voluntarily assumed.
	                    {{config('app.name')}} shall not be responsible for any direct, indirect, consequential, special, punitive, or other damages (whether liability is asserted in contract, tort, or otherwise), costs or expenses, including, without limitation, lost profits, data, loss of goodwill, loss of or damage to property, or claims of third parties, arising out of, in connection with, or relating to Your use of this Site or any third party site&nbsp; {{config('app.name')}} shall not be responsible for any threatening, defamatory, obscene, offensive, or illegal content or conduct of any other party or any infringement of another’s rights, including, without limitation, intellectual property or similar rights.&nbsp; In all events, the maximum liability of {{config('app.name')}} to a fee-paying user, if any, shall be the amount such user paid to {{config('app.name')}} within the immediately preceding twelve (12) month period.<br><br>
	                    Should You be dissatisfied with the Site or the content hereof or a third-party site and the content thereof, Your sole and exclusive remedy is to discontinue use of this Site or such third-party site.&nbsp; To the extent permitted by applicable law, the foregoing remedy shall apply even if {{config('app.name')}} knew or should have known of the possibility of damages to You by use of the Site or a third-party site.<br><br>
	                    BECAUSE SOME JURISDICTIONS DO NOT ALLOW THE EXCLUSION OF CERTAIN WARRANTIES, THE ABOVE LIMITATIONS MAY NOT APPLY TO YOU.<br><br>
	                    <h2>Force Majeure</h2><br><br>
	                    We are not responsible for any failure to perform because of unforeseen circumstances of causes beyond our reasonable control, including: <br>
	                    Acts of God, such as fire, flood, earthquakes, hurricanes, tropical storms, or other natural disasters; 
	                    War, riot, arson, embargoes, acts of civil or military authority, or terrorism;
	                    Fiber cuts;
	                    Strikes, or shortages in transportation, facilities, fuel, energy, labor, or materials;
	                    Failure of the telecommunications or information services infrastructure; and
	                    Hacking, SPAM, or any failure of a computer, server, network, or software for so long as the event continues to delay our performance.<br><br>
	                    <h2>Section 230 Notice</h2>  <br><br>
	                    You acknowledge Your responsibility to prevent minors under Your care from accessing harmful or inappropriate material.  You agree not to allow minors to view any such content, and You agree to take responsible measures to prevent them from doing so.  Numerous commercial online safety filters are available which may help users limit minors’ access to harmful or inappropriate material.  Pursuant to 47 U.S.C. § 230(d), You are hereby informed that You can research such services at websites such as:  http://www.getwise.org or http://www.child-internet-safety.com/internet_filters.php, among others.  Please note that We make no representation or warranty regarding any of the products or services referenced on such sites, and We recommend that You conduct appropriate due diligence before purchasing or installing any online filter.  You agree to take steps to prevent minors from viewing Our Website or the content received via Our Services if Your computer or mobile device can be accessed by a minor.  Finally, You agree that if You are a parent or guardian of a minor child, it is Your responsibility, not Ours, to keep any age-restricted content on Our Website or Services from being displayed or accessed by Your children or wards.<br><br>
	                    Pursuant to the Communications Decency Act (“CDA”), 47 U.S.C. § 230(c)(1), and court decisions interpreting the scope of the CDA, You acknowledge and understand that We operate as the provider of an interactive computer service.  Thus, We are immune from, and cannot be held responsible for, claims arising from the publication of Your Content (as well as including third party content).  We do not create such content, and We are not responsible for the publication of remarks or communications of third parties that may arguably rise to the level of being actionable under federal or state laws including, but not limited to, the publication of material that might be considered defamatory, or violative of privacy or publicity rights.  Note, that federal law allows Us to remove any content found to be offensive, defamatory, obscene or otherwise violative of Our policies, without impacting Our status as the provider of an interactive computer service.  In the event that any court finds that any third-party communication or third-party content on Our Website falls outside of the realm of the immunity provided by Section 230 of the CDA, this shall not be deemed to be a waiver of any legal protections provided by Section 230 for any and all other content posted on Our Website.  Nothing contained in this Agreement is intended to limit or alter the immunity from claims provided by Section 230 of the Communications Decency Act, and no third parties are intended to benefit from this Agreement between You and Us.<br><br>
	                    We respect the intellectual property rights of all parties and have adopted a policy regarding termination of repeat copyright infringers under the Digital Millennium Copyright Act.  Copies of Our Repeat Infringer Policy are available to Our Publishers upon request.<br><br>
	                    <h2>Violations of Terms</h2><br><br>
	                    {{config('app.name')}} reserves the right to block Your access to this Site and terminate Your account, if {{config('app.name')}} determines, in its sole discretion, that You have failed to comply with these terms of use, provisions, and conditions. This is in addition to all other remedies {{config('app.name')}} may have at law, in equity, or otherwise.<br><br>
	                </p>
	            </article>
	        </div>
	    </div>
	</div>
</div>
@endsection